-- AlterTable
ALTER TABLE `stats` ADD COLUMN `deposit` VARCHAR(191) NOT NULL DEFAULT '0',
    MODIFY `earning` VARCHAR(191) NOT NULL DEFAULT '0',
    MODIFY `balance` VARCHAR(191) NOT NULL DEFAULT '0',
    MODIFY `withdraws` VARCHAR(191) NOT NULL DEFAULT '0';
