export SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxcXhjYmlqcGlpeHRlZ2VtYXN6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY1MDIwNjkxMCwiZXhwIjoxOTY1NzgyOTEwfQ.bi6MLGDQR9nqPHMZL21-nnjlzyYCfry4rVpbC_YBjTM
export SUPABASE_URL=https://gqqxcbijpiixtegemasz.supabase.co
export DATABASE_URL=postgresql://postgres:davidbriggs00154@gmail.com@db.gqqxcbijpiixtegemasz.supabase.co:5432/postgres

npm run dev:watch