name: ci
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        run: |
          echo "Hello test"
          una -r
        shell: bash
